"""ExamplePlugin DB Changes

Revision ID: 3c17e9c5f27f
Revises: 
Create Date: 2017-08-31 13:36:06.847254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c17e9c5f27f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testPlugin',
    sa.Column('test', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testPlugin_Association',
    sa.Column('testPlugin_id', sa.Text(), nullable=True),
    sa.Column('openwrt_id', openwifi.guid.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['openwrt_id'], ['openwrt.uuid'], ),
    sa.ForeignKeyConstraint(['testPlugin_id'], ['testPlugin.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testPlugin_Association')
    op.drop_table('testPlugin')
    # ### end Alembic commands ###
